### PR TITLE
Disable CUDA awareness by default

### LINKED ISSUE #55: Discussion on Open MPI failures due to CUDA awareness
In open-mpi/ompi#7460 we found and reported that the CUDA-aware Open MPI (#54) is causing some mpi4py-fft tests to fail (see also [here](https://bitbucket.org/mpi4py/mpi4py-fft/issues/15/tests-failed-in-test_mpifftpy)). This is suggesting the decision of turning on CUDA awareness may cause issues for downstream ***CPU-only*** projects. I have one question and two proposals to remedy this before Open MPI (or mpi4py-fft?!) fixes the error.

Question for downstream package maintainers: Have you seen or received any bug report after we pushed out #54 recently? 

Proposals on possible fixes:
1. Restore the old `openmpi` package, and rename the current output `openmpi` to `openmpi-cuda`:
  - Pro: for CPU projects `openmpi` is readily usable as before
  - Con: for projects that support different flavors *and* GPU usage, you get one extra flavor to build against
  - Con: for openmpi-feedstock we'd generate one extra package for each supported platform
2. Keep the current recipe as is, but turn off the CUDA awareness by default (via setting `OMPI_MCA_opal_cuda_support=false` as suggested in https://github.com/open-mpi/ompi/issues/7460#issuecomment-590515467):
  - Pro: we have the same pro and avoid the cons above
  - Con: for GPU projects that need CUDA  awareness, the users need to remember setting `OMPI_MCA_opal_cuda_support=true`, but currently the feedstock has no documentation page to communicate this subtlety (plus it's likely users don't even read webpages here)

Tagging @conda-forge/hdf5 @conda-forge/h5py @conda-forge/mpi4py @conda-forge/fftw @conda-forge/dask-mpi. (I can only think of a few projects that support different MPI flavors, so please feel free to tag relevant parties.)

cc: @jakirkham @conda-forge/openmpi @conda-forge/mpi4py-fft for awareness

### PR DESCRIPTION
**Pull request by leofang**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Close #55.

### CODE REVIEW

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
@jakirkham I looked at the CI output but didn't find the post-link message shows up. Is this expected? 

I also tried installing drmaa locally, and didn't see the post-link message either...

**Comment by leofang** [comment]
@dalcinl Thanks. I thought about it too. Is 2462aa1 better?

**Comment by jakirkham** [comment]
> I looked at the CI output but didn't find the post-link message shows up. Is this expected?

Hmm...I wouldn't expect that. Maybe [raise a conda-build issue]( https://github.com/conda/conda-build/issues ) and see what they say?

**Comment by jakirkham** [comment]
We might also need [some code like this]( https://github.com/conda-forge/python.app-feedstock/blob/b0ef159c9401c6d933ea8678aa43d73006d1c54c/recipe/build.sh#L28-L32 ) to plugin this script.

**Comment by leofang** [comment]
@beckermr: Matt, any idea why the post-link script didn't print out to the console?

**Comment by jakirkham** [comment]
@leofang, did you already add the code above to the build script?

**Comment by leofang** [comment]
Seems to be working: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=126268&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=6d4b912b-175d-51da-0fd9-4d30fe1eb4e7&l=21371 but it looks weird, let me try not write to `.messages.txt`. 

It's odd that this extra code is needed but isn't documented!

**Comment by jakirkham** [comment]
Yeah the `.message.txt` is needed to avoid having log messages from packages intermingled with Conda output in an unreadable way.

**Comment by beckermr** [comment]
Yes you have to write to the messages.txt

File: recipe/post-link.sh [hunk 1]
```diff
@@ -0,0 +1,6 @@
+#!/bin/bash
+
+echo "\nFor Linux 64, Open MPI is built with CUDA awareness but this support is disabled by default." >> $PREFIX/.messages.txt
```
Comment (jakirkham) [inline recipe/post-link.sh]: I think `echo` needs `-e` to convert `\n` to a proper newline (as opposed to a literal in the output). Though IIRC this is something `bash` (maybe other shells too) support and `sh` won't respect it. An easy way to solve this across shells is to break `echo`s onto multiple lines as you have done in other cases here.

ref: https://unix.stackexchange.com/a/219274

Comment (leofang) [reply recipe/post-link.sh]: Right, I forgot. Thanks, John!

But, do you know why even with several `echo`s, the post-link message is still printed as a one-liner? See 
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=126303&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=6d4b912b-175d-51da-0fd9-4d30fe1eb4e7&l=21371
It doesn't seem to behave as expected...

Comment (dalcinl) [reply recipe/post-link.sh]: @leofang Use `printf` instead of `echo` for easy and correct newline printing.

About the bad output, It looks like a conda issue, it is likely executing a Python `print` on a byte string (note the `b'...`) prefix.

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

File: recipe/post-link.sh (hunk 1 above)
Comment (leofang) [reply recipe/post-link.sh]: I fixed the output. I agree it's a bug on conda/conda-build. I'm afraid no matter what we do here, we won't get a nicely formatted post-link message in the near future. Let's move on with this PR.

**Comment by jakirkham** [comment]
Thoughts @conda-forge/openmpi? 🙂

**Comment by jakirkham** [comment]
Do you have thoughts on how we could improve the messaging further? 🙂

**Comment by beckermr** [comment]
An activation script would be more noisy but in general there is not much we can do.

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
Rerendering never completed?!

@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
See here: https://github.com/conda-forge/openmpi-feedstock/runs/495849112?check_suite_focus=true

You are getting an error pushing to your repo.

**Comment by jakirkham** [comment]
How are we doing the push? Do we use `git@github.com:<user>/<repo>.git` or are we using `https://`? Asking as the latter IIRC does not work if the user has 2FA enabled.

**Comment by beckermr** [comment]
@jakirkham I have 2FA and have had no problems with it pushing to my branches...

**Comment by leofang** [comment]
Rerendered locally. Not sure what's wrong, though. I have activated my 2FA for a long time and never had a problem until now...Re-kicking it off just for testing.

@conda-forge-admin, please rerender

**Comment by leofang** [comment]
Alright, so looks like the bot was updated during this period, and without rerendering manually the new bot can't accept the job...Thanks, @beckermr!

But, why is the osx job cancelled? It says
> This job was temporarily blocked because it uses a Microsoft hosted agent (MacOS-10.13) that will be permanently removed on March 23rd, 2020.  See https://aka.ms/blocked-hosted-agent for more information.

Does it mean we can't build osx packages for the moment?

**Comment by beckermr** [comment]
@conda-forge/core @isuruf looks like azure is getting serious about this osx image issue

**Comment by leofang** [comment]
For this PR it's OK, though. The OS X package doesn't get any update other than a pure booking bump in the build number.

@dalcinl This is in your hands now.

**Comment by dalcinl** [comment]
> @dalcinl This is in your hands now.

What do you mean? Do you just want me to click the merge button?

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by jakirkham** [comment]
> looks like azure is getting serious about this osx image issue

@leofang I think this got fixed in conda-smithy 3.6.11. So a re-render should fix it.

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
@conda-forge-admin recipe lint

**Comment by beckermr** [comment]
@conda-forge-admin lint

**Comment by leofang** [comment]
@beckermr @jakirkham Thanks for the update! 

@dalcinl Yes, please feel free to merge this.

**Comment by leofang** [comment]
Ah, one more question: do you mind if I add myself to the recipe maintainer list?

**Comment by dalcinl** [comment]
> Ah, one more question: do you mind if I add myself to the recipe maintainer list?

YES, PLEASE!!! Do it right now and ping me back for merge.

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
@dalcinl Done.

**Comment by leofang** [comment]
@dalcinl All checks passed.

**Comment by jakirkham** [comment]
Thanks @leofang for the PR and everyone for all the reviews! 😄

**Comment by leofang** [comment]
Thanks to you all, @dalcinl @jakirkham @beckermr!

**Comment by leofang** [comment]
The post-link output is really ugly...
```bash
$ conda create -n mpi_test -c conda-forge python=3.7 mpi4py openmpi
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.7.12
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/leofang/miniconda3/envs/mpi_test

  added / updated specs:
    - mpi4py
    - openmpi
    - python=3.7


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2020.4.5.1 |       hecc5488_0         146 KB  conda-forge
    certifi-2020.4.5.1         |   py37hc8dfbb8_0         151 KB  conda-forge
    mpi-1.0                    |          openmpi           4 KB  conda-forge
    mpi4py-3.0.3               |   py37hbfacf26_1         647 KB  conda-forge
    openmpi-4.0.2              |       hdf1f1ad_4         3.9 MB  conda-forge
    setuptools-46.1.3          |   py37hc8dfbb8_0         634 KB  conda-forge
    xz-5.2.5                   |       h516909a_0         430 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         5.9 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-0_gnu
  ca-certificates    conda-forge/linux-64::ca-certificates-2020.4.5.1-hecc5488_0
  certifi            conda-forge/linux-64::certifi-2020.4.5.1-py37hc8dfbb8_0
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.34-h53a641e_0
  libffi             conda-forge/linux-64::libffi-3.2.1-he1b5a44_1007
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.2.0-h24d8f2e_2
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-7.3.0-hdf63c60_5
  libgomp            conda-forge/linux-64::libgomp-9.2.0-h24d8f2e_2
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-9.2.0-hdf63c60_2
  mpi                conda-forge/linux-64::mpi-1.0-openmpi
  mpi4py             conda-forge/linux-64::mpi4py-3.0.3-py37hbfacf26_1
  ncurses            conda-forge/linux-64::ncurses-6.1-hf484d3e_1002
  openmpi            conda-forge/linux-64::openmpi-4.0.2-hdf1f1ad_4
  openssl            conda-forge/linux-64::openssl-1.1.1f-h516909a_0
  pip                conda-forge/noarch::pip-20.0.2-py_2
  python             conda-forge/linux-64::python-3.7.6-h8356626_5_cpython
  python_abi         conda-forge/linux-64::python_abi-3.7-1_cp37m
  readline           conda-forge/linux-64::readline-8.0-hf8c457e_0
  setuptools         conda-forge/linux-64::setuptools-46.1.3-py37hc8dfbb8_0
  sqlite             conda-forge/linux-64::sqlite-3.30.1-hcee41ef_0
  tk                 conda-forge/linux-64::tk-8.6.10-hed695b0_0
  wheel              conda-forge/noarch::wheel-0.34.2-py_1
  xz                 conda-forge/linux-64::xz-5.2.5-h516909a_0
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1006


Proceed ([y]/n)? 


Downloading and Extracting Packages
openmpi-4.0.2        | 3.9 MB    | ############################################################################################################################ | 100% 
mpi4py-3.0.3         | 647 KB    | ############################################################################################################################ | 100% 
mpi-1.0              | 4 KB      | ############################################################################################################################ | 100% 
ca-certificates-2020 | 146 KB    | ############################################################################################################################ | 100% 
setuptools-46.1.3    | 634 KB    | ############################################################################################################################ | 100% 
certifi-2020.4.5.1   | 151 KB    | ############################################################################################################################ | 100% 
xz-5.2.5             | 430 KB    | ############################################################################################################################ | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: \ b' \nFor Linux 64, Open MPI is built with CUDA awareness but this support is disabled by default.\nTo enable it, please set the environmental variable OMPI_MCA_opal_cuda_support=true before\nlaunching your MPI processes. Equivalently, you can set the MCA parameter in the command line:\nmpiexec --mca opal_cuda_support 1 ...\n \n'
done
#
# To activate this environment, use
#
#     $ conda activate mpi_test
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```

**Comment by beckermr** [comment]
file a fix on the conda side I supposed

**Comment by leofang** [comment]
Thanks, Matt. I did already file an issue in https://github.com/conda/conda-build/issues/3883. I tried searching how pre-/post- link scripts are printed, but I couldn't figure it out...

**Comment by beckermr** [comment]
This happens in conda/conda, not conda/conda-build.

**Comment by leofang** [comment]
Ahhh, thanks for the pointer! Will take a look later.
